development:
  adapter: sqlite3
  database: db/blog_development.sqlite3
  pool: 5
  timeout: 5000

test: &TEST
  adapter: sqlite3
  database: db/blog_test.sqlite3
  pool: 5
  timeout: 5000
  
cucumber:
  <<: *TEST
